spring:
  application:
    name: content-ingestion
datasource:
  url: jdbc:h2:mem:contentdb
  driverClassName: org.h2.Driver
  username: sa
  password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
  flyway:
    enabled: false